### ISSUE TITLE
Create documentation for GUI on `readthedocs.io`

### ISSUE THREAD

**Issue by zuckerruebe** [SPF-OST/pytrnsys_gui#107]
As a user I would like the GUI to be documented on `readthedocs.io` (this is also the place where plain `pytrnsys` is documented).

The documentation should:

1. Explain what the GUI does
     1. Export of hydraulics
     2. Export of storage tanks
     3. Solve mass flow statically
2. Explain what the GUI doesn't do/what needs to be changed manually/what is done within `pytrnsys`
     1. ...?
3. Explain how the GUI relates to `pytrnsys`
4.  ...?

**Comment by zuckerruebe** [comment]
@danielcarbonell @martin-neugebauer Feel free to comment on and/or expand this issue.

**Comment by martin-neugebauer** [comment]
I'm fine with it being moved to readthedocs... I guess it shouldn't be too much work, since the documentation is already in the correct format.

**Comment by martin-neugebauer** [comment]
Concerning 2.: I'm not sure we need to explain what it doesn't do, as long as we explain what it does... If anything we can list features that we want to develop as an outlook.

**Comment by zuckerruebe** [comment]
...what it doesn't do with respect to `pytrnsys` or what you'll have to do manually I meant to say. As in: what it won't do automatically for you/what you'll still need to change in the ddcks (e.g. hydraulic control), etc. I'll try to rephrase.

**Comment by martin-neugebauer** [comment]
As agreed upon today, I'll merge both documentations on readthedocs

**Comment by zuckerruebe** [comment]
@martin-neugebauer : shall we close this?

**Comment by martin-neugebauer** [comment]
Yes.
