### ISSUE TITLE
Create GUI test for storage tank

### ISSUE THREAD

**Issue by martin-neugebauer** [SPF-OST/pytrnsys_gui#121]
As #119  happened, it made me aware that we need a test that emulates a user configuring a storage tank and make sure that this goes as intended. In the mentioned bug the program crashed upon removing heat exchangers and when placing port pairs on a Tes, i.e. the program was crashing during a basic task.

**Comment by ahobeost** [comment]
- [ ] prepare project with TES in it
- [ ] add heat exchanger to existing TES
- [ ] remove heat exchanger from existing TES
- [ ] add port pairs to existing TES
- [ ] add new TES to diagram

**Comment by ahobeost** [comment]
@sebastian-swob: The views and mocks in the following file should be separated to make it easier to reuse individual pieces.
https://github.com/SPF-OST/pytrnsys_gui/blob/master/tests/trnsysGUI/testStorageTank.py

As part of this issue, it would especially be interesting to prepare the editor as a callable mock.
