### ISSUE TITLE
Create manual release test issue template

### ISSUE THREAD

**Issue by zuckerruebe** [SPF-OST/pytrnsys_gui#123]
As a developer I want to ensure that our releases are as error-free as possible. For that reason, we should define some tests that should be performed manually before each release (along the lines of drop a collector, tank with, say, a port and a heat exchanger and a hot water outlet into a project and run the simulation). The tests should be written up as a GitHub issue, so that we can copy that issue before each release and report test results for that specific release on that copied issue.

The issue template should be linked to this issue so that it can be found.

**Comment by zuckerruebe** [comment]
The template is #125 .

**Comment by martin-neugebauer** [comment]
Done through #161
