### ISSUE TITLE
Mfr of pump in mass flow solver named differently in different places leading to error

### ISSUE THREAD

**Issue by martin-neugebauer** [SPF-OST/pytrnsys_gui#126]
![image](https://user-images.githubusercontent.com/67690903/134304299-ab192c8a-2c7b-473b-822d-a5b43609b91e.png)

**Comment by martin-neugebauer** [comment]
New project was opened, diagram made, pump renamed, then ran mass flow solver -> error

**Comment by zuckerruebe** [comment]
@martin-neugebauer I believe this has been fixed with #127. That was this issue, right?

**Comment by martin-neugebauer** [comment]
Yes, thanks!
