### ISSUE TITLE
Update header entries in GUI.py

### ISSUE THREAD

**Issue by martin-neugebauer** [SPF-OST/pytrnsys_gui#134]
![image](https://user-images.githubusercontent.com/67690903/135882848-0737c2b9-b344-4d40-bff7-fc9c844d3074.png)

We should update or remove these

**Comment by zuckerruebe** [comment]
I'd say remove.

**Comment by martin-neugebauer** [comment]
I'm also in favor of deleting, we just need to make sure to not create issues with any of these items:

![image](https://user-images.githubusercontent.com/67690903/136000793-23345a09-fdad-4bda-ad5c-7d4794c06185.png)

At the least the version appears to be referenced there
![image](https://user-images.githubusercontent.com/67690903/136000877-904b468b-26fb-4b51-97d6-b3b70264c87a.png)

**Comment by martin-neugebauer** [comment]
Maybe the best would be to link the online documentation from the Help and remove the rest. I don't think we want yet another place where we need to manually update the actual version number.

**Comment by zuckerruebe** [comment]
Done.
