### ISSUE TITLE
Double pipe components

### ISSUE THREAD

**Issue by martin-neugebauer** [SPF-OST/pytrnsys_gui#135]
Subissues:
- [x] #139 
- [x] #146 
- [x] #147 

For district heating projects we need double pipe components, since the hot and cold parts of these pipes will interact, which is not captured by one of our standard pipes. We envision something like:

![IG_1](https://user-images.githubusercontent.com/67690903/136029845-0c3f129e-534b-405e-8604-67358ff61c3a.PNG)

This means we need to implement three new components plus the possibility to connect those directly (and not via a normal pipe, which is the case at the moment).

1. Single-double pipe coupler

![IG_2](https://user-images.githubusercontent.com/67690903/136030402-2192d738-6ef1-4bc8-aa81-56f200b97966.PNG)

This component should feature ports to connect to single pipes on one side and connect to double pipe components on the other side. For the mass flow solver this behaves like a four port item.

2. Double pipe

![IG_3](https://user-images.githubusercontent.com/67690903/136031151-87ec9d8c-53db-43d2-a1d5-582f645aa077.PNG)

This is the actual double pipe and it connects to another double pipe component on each side. For the mass flow solver this behaves like a four port item.

3. Double T piece

![IG_4](https://user-images.githubusercontent.com/67690903/136032091-9fe6d1c6-d259-458e-af2b-ab06f1a8c08f.PNG)

This is a T piece for double pipes. It connects to double pipe components on three sides. For the mass flow solver it behaves like two T pieces.

The double pipe components should connect directly and somehow snap onto each other.

**Comment by martin-neugebauer** [comment]
Thinking of it, we probably also need a corner element.

**Comment by zuckerruebe** [comment]
Out of curiosity: are the mentioned interactions beneficial/wanted or rather not but due to the fact that the insulation cannot be perfect?

**Comment by mschu84** [comment]
@zuckerruebe the pipes in such low temperature networks are normally not insulated. They have low losses as their temperature is close to ground temperature. But of course they influence each other - and for very low temperatures in the networ (e.g. around 0) we will even have gains from the ground in winter. (did you mean this thermal interactions?)

**Comment by zuckerruebe** [comment]
> 
> 
> @zuckerruebe the pipes in such low temperature networks are normally not insulated. They have low losses as their temperature is close to ground temperature. But of course they influence each other - and for very low temperatures in the networ (e.g. around 0) we will even have gains from the ground in winter. (did you mean this thermal interactions?)

Yes, exactly, thanks.

**Comment by FlorianRueschOst** [comment]
at least for the beginning the modified type 9511 (from Mattia, original type was 951 ground burried double pipe from tess) shall be used for the double pipes....

**Comment by SPF-OST** [comment]
They look nice. I would use red on top and blue on the bottom
