### ISSUE TITLE
Enable static checks for key files

### ISSUE THREAD

**Issue by zuckerruebe** [SPF-OST/pytrnsys_gui#136]
Enable them for
- [x] `PortItem.py`
- [x] `Connection.py`
- [x] `BlockItem.py`
- [x] `storageTank` module

**Comment by zuckerruebe** [comment]
@martin-neugebauer @simonschlaepfer Feel free to join in, the perfect story for a rainy and/or hung over day. ;)

**Comment by martin-neugebauer** [comment]
pylint encounters issues on master (because of pending changes in pytrnsys). Let's leave this issue open as reminder until pylint runs through on master
