### ISSUE TITLE
Cosmetic corrections to mass flow labels

### ISSUE THREAD

**Issue by martin-neugebauer** [SPF-OST/pytrnsys_gui#137]
As a feedback to my pytrnsys presentation I received the commment that it would be nicer if the mass flow rates in the labels of the mass flow visualizer were in "kg/h" instead of "kg/Hr" and rounded (like the temperature) to not have a decimal point.

**Comment by zuckerruebe** [comment]
Done. Both numbers now are rounded to one decimal digit.
