### ISSUE TITLE
Process data tab not working in GUI

### ISSUE THREAD

**Issue by Tushar13992** [SPF-OST/pytrnsys_gui#144]
Dear Developers 

I tried the pytrnsys gui for the sample project solar_dhw and was successful in running the project after a minor correction that I would like to mention below: 

*************************************
*** Inputs from hydraulic solver ****
*************************************
EQUATIONS 3
Tdp1In_Tes1 = TPiTesDhwIn ! @connectDdck
Mfrdp1_Tes1 = MfrPiTesDhwIn ! @connectDdck
Tdp1InRev_Tes1 = TPiTesDhwOut ! @connectDdck
EQUATIONS 3
Thx1In_Tes1 = TPiColOut ! @connectDdck
Mfrhx1_Tes1 = MfrPiColOut ! @connectDdck
Thx1InRev_Tes1 = TPiTesToColl ! @connectDdck
CONSTANTS 2
zAux1_Tes1=0.00 !connectDDck
qAux1_Tes1=0.00 !connectDDck

This is a small code snippet from the file DHW.ddck which is available in the sample project directory. Only a small change is needed...in the original version, it is TPiTesToCol ( with only one 'l' after Co ). I changed it to TPiTesToColl ( double 'l') and it worked as I found that the variables defined in the hydraulic solver had double 'l'. 

But one thing which doesn't work at the moment is the Process data tab in the toolbar. Even after defining everything in the process.config file, there is an error saying that 

![image](https://user-images.githubusercontent.com/49749355/136575329-da4595e0-0a6a-413b-bbb8-5515b0317355.png)

Has anybody encountered the same problem or is processing function and plotting still in progress for GUI? 

Regards 

Tushar

**Comment by martin-neugebauer** [comment]
Hi Tushar, thanks for your feedback. 

We need to correct the error in the example case, thanks for noting.

Concerning the "process" button, it worked before, but we didn't use it too much, since we now mustly run short scripts. We should decide whether to keep it functional or remove it.

You can find a short script to execute what you define in the process config file here:
[ProcessMain.zip](https://github.com/SPF-OST/pytrnsys_gui/files/7312114/ProcessMain.zip)

**Comment by Tushar13992** [comment]
Dear Developers 

I created a process.config file and placed the python script where it should. But I am getting this error. Have you faced this error before ? Or do you have any suggestions on how to resolve this? ( PS: when I run the script separately in another folder from pytrnsys, not GUI, it works just fine!!) 

 
![image](https://user-images.githubusercontent.com/49749355/136921930-81638ffd-802b-4cc8-acbb-c7c5e945f3d2.png)

Regards 

Tushar

**Comment by Tushar13992** [comment]
Yes sure. Attached below!
[process.zip](https://github.com/SPF-OST/pytrnsys_gui/files/7328399/process.zip)

**Comment by Tushar13992** [comment]
Dear Developers 

Could you find any solution to the problem? 

Regards 

Tushar

**Comment by martin-neugebauer** [comment]
Hi Tushar,
Sorry, the issue got a bit lost among many others. We can have a closer look next week. But do I understand "when I run the script separately in another folder from pytrnsys, not GUI, it works just fine!!" correctly in the sense that you can work with it just not in the GUI directory?

**Comment by Tushar13992** [comment]
Hi Martin

By that statement, I meant that it works just fine when I run it in from the pytrnsys folder ( normally without the GUI ). And when I run the process file in the folder where the simulations were performed using GUI, the scripts shows me the error I mentioned above.

**Comment by martin-neugebauer** [comment]
In the project folder you sent me, the solardhwsampleproject.zip\solar_dhw_GUI\temp\DHW_MO.Prt file looks like this:
![image](https://user-images.githubusercontent.com/67690903/142629588-6a52cb06-bc26-418f-a5bd-4871c599e3bf.png)
So it does not contain any month. If I let the simulation complete for the year, the same file looks like this:
![image](https://user-images.githubusercontent.com/67690903/142629718-f554bc88-42de-41e6-984c-fe5b10c95ca6.png)
If the file is empty, it leads to the error you encountered. We should catch this error and return a warning.

**Comment by zuckerruebe** [comment]
@Tushar13992 : Can we close this, is it fixed?

**Comment by Tushar13992** [comment]
@zuckerruebe , please give me a few days to have a look at it again. If it doesn't work with the tips you gave, then I will let you know.

**Comment by zuckerruebe** [comment]
@Tushar13992 : sure, thanks for checking!

**Comment by Tushar13992** [comment]
@zuckerruebe I think you were right, the error is only due to the missing information in the prt file. Because when there is information the plotter normally should work fine as it reads just from the data file.

**Comment by martin-neugebauer** [comment]
Moved to https://github.com/SPF-OST/pytrnsys/issues/71
