### ISSUE TITLE
Hydraulic ddck not updating port names 

### ISSUE THREAD

**Issue by Tushar13992** [SPF-OST/pytrnsys_gui#178]
Hi Martin 

I tried to create a new project of solar DHW using pytrnsys as per the instructions mentioned in the manual. This is how I did it: 
1. Created the diagram as per the instructions by placing the respective components in the correct order. 
2. I copied the ddck from the already existing sample project solar dhW to the respective ddcks of the new project. 
3. Exported the hydraulic and then the final ddck.
4. Ran the simulation and it crashes within one second with the following error: 
![image](https://user-images.githubusercontent.com/49749355/141452686-6035b076-3128-4ff3-8e7d-2bd797deea09.png)

The reason for the error is that while exporting hydraulic.ddck, it is not taking into consideration the name of the ports mentioned in the ddck of the collector and instead assigns a dummy name as shown below: 

![image](https://user-images.githubusercontent.com/49749355/141453066-b017ff2b-87e2-46c4-99d3-7098b0e64d7f.png)

While in the hydraulic.ddck of the original project, it is as follows: 
![image](https://user-images.githubusercontent.com/49749355/141453444-1a5f8995-35d2-40a3-bacc-31549ece9070.png)

Is there a step that I am missing? Or is there some error in the hydraulic.ddck code. Please let me know how to resolve this issue.

**Comment by martin-neugebauer** [comment]
Hi Tushar,

Did you rename pipes?

![image](https://user-images.githubusercontent.com/67690903/141463824-ebb0d082-2a5c-429f-a7ef-6397307911eb.png)

**Comment by martin-neugebauer** [comment]
Each library component expects the input pipes to have a certain name, e.g. for type 1:
![image](https://user-images.githubusercontent.com/67690903/141464627-4cc47264-9ff8-44a7-bf4f-e8b687fdc651.png)
This means that the pipe going into the collector needs to be called PiColin, then TPiColIn will be automatically generated. We are planning to make the pipe naming automatic, but for now the user still needs to do it manually.

**Comment by martin-neugebauer** [comment]
Discussed in a video call.
