### ISSUE TITLE
GUI crashes upon hydraulic export if a PV module is in the diagram

### ISSUE THREAD

**Issue by martin-neugebauer** [SPF-OST/pytrnsys_gui#179]
The PV is treated like a hydraulic object with nodes, but doesn't have any, so this happens:

![image](https://user-images.githubusercontent.com/67690903/141495020-a4ad30e1-dbbe-4b1c-9223-1eb46e56b0be.png)

**Comment by zuckerruebe** [comment]
@martin-neugebauer tested this and it was fixed.
