### ISSUE TITLE
Naming component like an existing ddck folder crashes the GUI

### ISSUE THREAD

**Issue by martin-neugebauer** [SPF-OST/pytrnsys_gui#180]
If a tank is named like a folder that already exisits in the ddck directory, the program crashes:

![image](https://user-images.githubusercontent.com/67690903/141495433-17e029fc-a178-451c-9bd2-047eb27799e8.png)

**Comment by zuckerruebe** [comment]
Maybe we don't remove/name folders when deleting/renaming storage tanks.
