### ISSUE TITLE
pytrnsys GUI crash

### ISSUE THREAD

**Issue by Tushar13992** [SPF-OST/pytrnsys_gui#187]
Hi Martin 

I was trying something with the diagram creator. I joined all the components but did not put any ddck files in the respective folders. Then I just saved the diagram and then tried to open the project again. It crashes all the time. I am attaching here the json file in zip format below. 

[Trial.zip](https://github.com/SPF-OST/pytrnsys_gui/files/7569777/Trial.zip)

**Comment by martin-neugebauer** [comment]
Is there an empty ddck folder in the project folder? Does the json have the same name as the project folder (i.e. Genopt_v2/Genopt_v2.json)?

**Comment by martin-neugebauer** [comment]
I was able to open it without crashes.... Are you using version 0.9.9?

**Comment by Tushar13992** [comment]
![image](https://user-images.githubusercontent.com/49749355/142623086-c58f965f-5577-48de-bf49-2b641f052819.png)

Yes, it is the same folder and yes the ddck folders are empty at the moment.

**Comment by Tushar13992** [comment]
And I think my version is 0.9.7 as seen in the screenshot below: 

![image](https://user-images.githubusercontent.com/49749355/142623618-46545129-ab69-4e21-94ba-f14ed28f6e98.png)

**Comment by martin-neugebauer** [comment]
Yes, you have version 0.9.7.

Please upgrade to 0.9.9 by following the section "Upgrading from one patch version to the next within the same minor version" in the readme (need to scroll down) of https://github.com/SPF-OST/pytrnsys_gui

Please try to open it again after upgrading.

**Comment by Tushar13992** [comment]
Yes, that worked after updating the patch version. Thanks for the help, Martin!

**Comment by martin-neugebauer** [comment]
No problem!

**Comment by Tushar13992** [comment]
I want to add a minor bug here. If I make a ddck of any component and I put it in the respective folder and then I try to load the same ddck from the same folder. It asks me to overwrite the file or cancel. If I choose to overwrite and take the same ddck, it crashes. If I put the ddck in any other folder and then load it, it then copies it to the respective components folder and there is no issue.

**Comment by zuckerruebe** [comment]
@martin-neugebauer : shall we move this back to "To Do"?

**Comment by martin-neugebauer** [comment]
@zuckerruebe Or make a new dedicated issue?

**Comment by zuckerruebe** [comment]
@martin-neugebauer : Even better, I'll do that.
