### ISSUE TITLE
Can connect hot to cold port

### ISSUE THREAD

**Issue by zuckerruebe** [SPF-OST/pytrnsys_gui#197]
As a user, I shouldn't be able to connect a hot port item with a cold port item, i.e. do the following:

![image](https://user-images.githubusercontent.com/11159050/144026197-9ed22a36-14d3-48e9-b5ac-0a96174d52f8.png)

Of course, when going through intermediate "generic" ports (i.e. not hot or cold) that's kind of OK. But direct connections don't make sense.

**Comment by zuckerruebe** [comment]
@mschu84 : Do you think this should be fixed or should it actually be allowed?

**Comment by martin-neugebauer** [comment]
Should be allowed
