### ISSUE TITLE
Crash when exporting hydraulic file if there are unconnected ports.

### ISSUE THREAD

**Issue by zuckerruebe** [SPF-OST/pytrnsys_gui#200]
See title.

**Comment by zuckerruebe** [comment]
@martin-neugebauer , @simonschlaepfer , @mschu84 , @danielcarbonell : Could anyone please test that this is fixed on master? You might have to pull first. Thank you. :*

**Comment by PuaYongHao** [comment]
@zuckerruebe This is fixed with the commit `Don't crash when trying to export unconnected hydraulic.` on 21/12/2021.
