### ISSUE TITLE
Export variables instead of numerical values for double pipes

### ISSUE THREAD

**Issue by martin-neugebauer** [SPF-OST/pytrnsys_gui#205]
At the moment numerical values are exported into the hydraulic.ddck for the parameters and inputs of double pipes (type 9511). This should be changed to variables of the same name for every double pipe and a central place for the definition of these variables.

**Comment by martin-neugebauer** [comment]
@mschu84

**Comment by mschu84** [comment]
the following variables from weather data file used as parameter for double pipe: 
        tSurfArg = 7.96            -> name in weather data ddck: TambAvg  
        amplSurfAvg = 13.32   -> name in weather data ddck: dTambAmpl
        dayMinSfT = 36           -> name in weather data ddck: ddTcwOffset
