### ISSUE TITLE
Remove `Control` and `MasterControl` classes.

### ISSUE THREAD

**Issue by zuckerruebe** [SPF-OST/pytrnsys_gui#213]
Ase a developer I'd like to remove these deprecated classes: they cannot currently be dragged into a diagram any more. When a control or master control object should be decoded when opening a project, they should be skipped and a warning to that effect logged to the console.

**Comment by zuckerruebe** [comment]
@martin-neugebauer : sounds about right?

**Comment by martin-neugebauer** [comment]
Absolutely. :-)

**Comment by ahobeost** [comment]
This is the current Warning:
"Warning: BlockItem: 'MasterControl' is no longer supported in the GUI."
