### ISSUE TITLE
Give ports names and nominal flow directions ("input"/"output") and add dialog to display in GUI

### ISSUE THREAD

**Issue by zuckerruebe** [SPF-OST/pytrnsys_gui#223]
As a developer and part of #222 I'd like ports have a name and nominal flow directions (i.e. are they an "input" port or an "output" port).

As a user, I'd like to be able to inspect the name and flow direction of a component's ports with a small dialog showing me the information in a table.

**Comment by martin-neugebauer** [comment]
There is already some information shown in the lower left widget when hovering above a port with the cursor. We should adapt/extend this feature.

**Comment by martin-neugebauer** [comment]
In this widget we would like to show the name of the port and whether it is an in- or output. What would also be nice is if all ports connected to the one hovered above would lighten up.

**Comment by zuckerruebe** [comment]
I'd suggest proceeding as follows:

- [ ] Add `name` and `type` (an `Enum`) to model (not graphical) `PortItem`. Pick dummy names for now (ofc, if you think you know a good name pick that one)
- [ ] Restrict ourselves to single pipe port items when highlighting all the internally connected pipes. Use `InternalPiping` and `_getInternallyConnectedPortItems` (make public, i.e. rename to `getInternallyConnectedPortItems`) for finding internally connected port items
- [ ] Let's discuss whether and how to extend this to double pipe port items
