### ISSUE TITLE
Crash when connecting boiler

### ISSUE THREAD

**Issue by martin-neugebauer** [SPF-OST/pytrnsys_gui#230]
Trying to connect a boiler leads to 
![image](https://user-images.githubusercontent.com/67690903/149969820-975008ea-957a-4c87-bf6a-f0fdc60401c8.png)
@zuckerruebe Could you have a look?
@PuaYongHao This is what you showed me.

**Comment by PuaYongHao** [comment]
@martin-neugebauer This is fixed when you added ```getInternalPiping``` to ```Boiler.py``` under the commit, ```Gave ports meaningful names and added numbers to ExternalHx sides```.

```
   def getInternalPiping(self) -> InternalPiping:
        inputPort = _mfn.PortItem("input", _mfn.PortItemType.INPUT)
        outputPort = _mfn.PortItem("output", _mfn.PortItemType.OUTPUT)

        pipe = _mfn.Pipe(self.displayName, self.trnsysId, inputPort, outputPort)

        return InternalPiping([pipe], {inputPort: self.inputs[0], outputPort: self.outputs[0]})
```

**Comment by martin-neugebauer** [comment]
Great! :-D
