### ISSUE TITLE
Corrected in- and outputs lead to incorrect connections in diagrams

### ISSUE THREAD

**Issue by martin-neugebauer** [SPF-OST/pytrnsys_gui#234]
Previously there were icons where the ports labelled as in- or outputs in the respective class were actually labelled incorrectly. This did not matter, since the list in which the ports were allocated did not really have any meaning. Their index simply determined if they belonged together.

This was now corrected for a few icons. This, however, leads to incorrect connections in already existing diagrams:
![image](https://user-images.githubusercontent.com/67690903/151325501-73d3ea03-6d4d-4079-a160-87583171875e.png)

@zuckerruebe Do you see a way of automatically correcting these errors during the loading of a json-file? (Maybe identified through the version number?)

**Comment by zuckerruebe** [comment]
@martin-neugebauer : it's probably too late for that now? Or: why did we never do this?

**Comment by martin-neugebauer** [comment]
I think one argument for not doing this is transparency: Users connected pipes to what they thought was the input, while it from the GUI-POV it was the output. On the other hand some users might have already considered it as the output (e.g. in a heat exchanger). Since the hydraulic connection was determined via pipe names, there is no way of knowing what the users assumed in the GUI, so now they see how it's actually connected and can correct if needed.

**Comment by zuckerruebe** [comment]
OK...so should we close the issue, then?
