### ISSUE TITLE
Disable automatic creation of hydraulic and updating of run.config when launching simulation from GUI

### ISSUE THREAD

**Issue by martin-neugebauer** [SPF-OST/pytrnsys_gui#242]
When a simulation is launched from the GUI, the hydraulic.ddck-file is exported, if there is not already a file of this name and the run.config-file is updated. This interferes with the user having their own hydraulic.ddck-file with an alternative name (which might be relevant to avoid overwriting edited hydraulic files). This automatism should be disabled.

**Comment by zuckerruebe** [comment]
Done.
