### ISSUE TITLE
single double connector temperature assignment

### ISSUE THREAD

**Issue by maikeSchubert** [SPF-OST/pytrnsys_gui#252]
fix mass flow direction in single-double connector to positiv from single to double pipe for hot and negative for single to double pipe for cold such that it doesn't depend of the rotation state of the connector. 
note: double pipes should also indicate their nominal flow direction

**Comment by zuckerruebe** [comment]
The first part (mass flow directions) is done. For the second part (nomal mass flow indication) see
1. https://github.com/SPF-OST/pytrnsys_gui/issues/337
2. https://github.com/SPF-OST/pytrnsys_gui/issues/338
