### ISSUE TITLE
automatic pipe naming too long

### ISSUE THREAD

**Issue by maikeSchubert** [SPF-OST/pytrnsys_gui#270]
In a new project with the automatic component naming the automatically generated pipe names are too long and have to be modified manually. Automatic pipe namings should lead to a running mass flow solver dck otherwise it is not very useful.

**Comment by martin-neugebauer** [comment]
@YongHao1999 Didn't we ensure exactly that?

**Comment by martin-neugebauer** [comment]
@maikeSchubert How long are they? Longer than 15 or longer than 20 characters?

**Comment by maikeSchubert** [comment]
@martin-neugebauer they get longer than 20 characters when in the hydraulic file MFR and _A is added! Such the pipe names should be max 15 when the final variables should be below 20 characters because we always have this variable MfrPipeName_A thing

**Comment by martin-neugebauer** [comment]
OK, I think I forgot about the ``_A``, I thought we'd only attach ``Mfr_``. Stupid TRNSYS limits...

**Comment by martin-neugebauer** [comment]
This makes it really hard to give meaningful names... You have 20 characters, but you need to leave space for ``Mfr``, ``Pi``, ``_`` and ``_A``, so you have 12 characters left for two component names. That makes six characters for a component, minus two characters we should reserve for ID numbers. So we have four characters for default component names... Get ready for more ``Cntr``!
@PuaYongHao Could you look into reducing the default names from max. 5 to max. 4 characters? This should fix this.

**Comment by PuaYongHao** [comment]
> This makes it really hard to give meaningful names... You have 20 characters, but you need to leave space for `Mfr`, `Pi`, `_` and `_A`, so you have 12 characters left for two component names. That makes six characters for a component, minus two characters we should reserve for ID numbers. So we have four characters for default component names... Get ready for more `Cntr`! @PuaYongHao Could you look into reducing the default names from max. 5 to max. 4 characters? This should fix this.

Sure. :)

**Comment by PuaYongHao** [comment]
I have reduced the default names to max. 4 characters. Please let me know if there is anything that I can help with.
