### ISSUE TITLE
Connect temperatures through pipes using the same mechanism as for mass flow

### ISSUE THREAD

**Issue by zuckerruebe** [SPF-OST/pytrnsys_gui#278]
As a user I would like not only mass flows but also temperatures to be correctly connected when connecting two components via a pipe.

Unlike mass flows there is an additional "complication" for temperatures: they are not conserved. For any given set of input temperatures we can have any set of output temperatures (subject to the physics of the component of course, but the GUI cannot know about that).

Therefore we need to specify the temperatures at the output ports. The placeholder syntax for ddck files should be extended to also allow statements like the following:

```
@temp(condOut) = ...
```

where the right-hand side (RHS) can be any expression.

Reversible components need also to be able to give the "output" temperature for reverse flows (i.e. the temperature at their nominal inputs). For that reason the following statements should also be allowed:

```
@revtemp(in) = ...
```

(think of the `in` as a heat exchanger's, e.g.)

The reason to have both `@temp` and `@revtemp` is that it allows `pytrnsys` to sanity-check that `@temp` is only ever given an input port and `@revtemp` an output port.

A line like

```
@temp(condOut) = ...
```

in a ddck file should be replaced with something like

```
THPCondOut = ...
```

in the final dck file (**this means we'll also have to pay attention to the length of the port names**, something we didn't have to do until know) **and** the input temperature (assuming the pipe was connected starting at `condOut`, otherwise the reverse input temperature) of the pipe connected to `condOut` in the generated hydraulic ddck must be set to `THPCondOut` like so:

```
UNIT 462 TYPE 931
!HP_DH
PARAMETERS 6
diHP_DH
LHP_DH
UHP_DH
RhoWat
CPWat
20
INPUTS 4
THPCondOut
MfrHP_DH_A
TRoomStore
0,0
***Initial values
20 0.0 20 -1000
```

Notice how the reverse input temperature of the above pipe is set to an unphysical -1000 degrees celcius. This is to ensure that if this irreversible component (i.e. the heat pump) is ever operated in a reverse fashion **the simulation will yield clearly unphysical results**. Whether a component can be operated in a reverse fashion and ultimately whether there will be meaningful reverse temperatures in the exported pipes is determined by the presence or absence of respective `@revtemp` expressions in the ddck files.

`@revtemp(in)` should, e.g., in a collector called "Col" be replaced with `rTColIn` (notice the "r").

For the "_mfs.ddck" file (export for mass flow solver only) the pipes' temperatures should all be set to constant, say, 20 degrees celcius direclty in the pipe definitions like so:

```
!HP_DH
PARAMETERS 6
diHP_DH
LHP_DH
UHP_DH
RhoWat
CPWat
20
INPUTS 4
0,0
MfrHP_DH_A
TRoomStore
0,0
***Initial values
20 0.0 20 20
```

The replacement values for the temperatures (both "normal" and reverse) should be read from the placeholder values JSON file as is done for inputs ATM. Generating the values in the JSON file for outputs is trivial because we don't need to look at the connected pipes to generate them. We just generate them from the component name and port names: `[r]T{componentName}{portName}`.

It's only when generating the hydraulics or "_mfs.ddck" that we need to look at connecting pipes.

**Last but not least**: the output expressions should, like the input expressions, also accept a default value for backwards compatibility, e.g. `@temp(out, THpCondOut)`. The default should be optional (we should've done that for inputs, too, shouldn't we have? **What do you guys think?**) as one might want to explicitely choose to make a new component usable from the GUI only.

**Comment by zuckerruebe** [comment]
@martin-neugebauer @PuaYongHao @danielcarbonell @jschmidl @maikeSchubert. Feel free to add your thoughts if you're interested and have time.

**Comment by zuckerruebe** [comment]
Instead of hardcoding the unphysical -1000 degrees celcius we should probably introduce a `rTNotReversible` constant with that value.

**Comment by martin-neugebauer** [comment]
I tried to break it down a bit (feel to free to extend):
- [ ] #280 
- [ ] #281 
- [ ] #282 
- [ ] #283

**Comment by zuckerruebe** [comment]
We should have all "connections" in one place to simplify debugging the connections like we did previously:

```
EQUATIONS 5
*** Black box component temperatures
TTesPortLeft50=1
TTesPortLeft10=1
TInHx=1
TCol=1
THP=1
```
