### ISSUE TITLE
storage Hx does not connect to the fluid properties

### ISSUE THREAD

**Issue by danielcarbonell** [SPF-OST/pytrnsys_gui#325]
When I add a loop of brine into the heat exchanger that connects to the storage and I make an export of the TES, the cphx1_Tes1 remains equal to cpwater instead of cpbrine. Same for density.

Instead of this
Cphx1_Tes1=cpwat
Rhohx1_Tes1=rhowat
it should be 
Cphx1_Tes1=cpbri     
Rhohx1_Tes1=rhobri

**Comment by zuckerruebe** [comment]
This is fixed on master.
