### ISSUE TITLE
Exporting Tes ddck makes GUI crash

### ISSUE THREAD

**Issue by martin-neugebauer** [SPF-OST/pytrnsys_gui#330]
Clicking `Export ddck` in tes dialogue leads to

![grafik](https://user-images.githubusercontent.com/67690903/199749510-cdbffa43-cc1e-4649-83ab-99650e8775a9.png)

The project for which this happens is attached
[hotTes.zip](https://github.com/SPF-OST/pytrnsys_gui/files/9930145/hotTes.zip)

**Comment by martin-neugebauer** [comment]
@zuckerruebe Could you have a look?

**Comment by zuckerruebe** [comment]
This is fixed on master.
