### ISSUE TITLE
Make opening dialogue always appear on top

### ISSUE THREAD

**Issue by martin-neugebauer** [SPF-OST/pytrnsys_gui#35]
When launching the GUI the opening dialogue window is often hidden behind other windows. We should make it always appear on top.

**Comment by zuckerruebe** [comment]
I tried doing something to this effect, but I'm not convinced it's always working. What's the other's experience?

**Comment by martin-neugebauer** [comment]
Sorry, I closed it, because it was marked as "done". I think for me it works, but I'll keep track on that. In the meantime I think we should keep it open.

@danielcarbonell @mschu84 What's your experience?

**Comment by mschu84** [comment]
For me it worked also

**Comment by zuckerruebe** [comment]
OK, if it works for two out of three power users then I declare it to bee good enough. ;)
