### ISSUE TITLE
Reusing ddcks?

### ISSUE THREAD

**Issue by ahobeost** [SPF-OST/pytrnsys_gui#430]
Currently, ddcks need to be  copied into specific folders.
Even if the contents is identical.
It would be meaningful to reduce this workload

Possible solutions:
- $SOMEDIR path\to\ddck [as \<component name\>]
- automating the creation of relative links to the file (otherwise still copying required).
- automate copying

**Comment by zuckerruebe** [comment]
Actually, for the ice grid case this issue wouldn't help much, as the copied ddcks differ in the profile they're referring to.

**Comment by ahobeost** [comment]
I disagree, as we have the case where multiple sinks are turned off.

**Comment by ahobeost** [comment]
This has been implemented in https://github.com/SPF-OST/pytrnsys/pull/158.
