### ISSUE TITLE
Gui Crash: mass flow solver issues

### ISSUE THREAD

**Issue by ahobeost** [SPF-OST/pytrnsys_gui#432]
![grafik](https://user-images.githubusercontent.com/122869062/227213772-8e6babae-a389-419f-844b-113e684c5da2.png)

**Comment by ahobeost** [comment]
@zuckerruebe: please check the following fix.
https://github.com/SPF-OST/pytrnsys_gui/commit/b9b97e20026483bf45a98501a2417ae2ce3c5d9d

**Comment by zuckerruebe** [comment]
> @zuckerruebe: please check the following fix. [b9b97e2](https://github.com/SPF-OST/pytrnsys_gui/commit/b9b97e20026483bf45a98501a2417ae2ce3c5d9d)

I wholeheartedly approve.
