### ISSUE TITLE
SolarPropIceSlurry example cannot be run using only the massflowsolver.

### ISSUE THREAD

**Issue by sebastian-swob** [SPF-OST/pytrnsys_gui#565]
When running this example, there are errors due to incorrect amounts of equations from declared ones.
![image](https://github.com/user-attachments/assets/8cb150ac-9194-4b32-b890-4f5378a567df)

**Comment by ahobeost** [comment]
This error is due to the amount of equations set in the trndll.
One needs to increase this and recompile it.
