### ISSUE TITLE
Containment for mass flow visualizer

### ISSUE THREAD

**Issue by martin-neugebauer** [SPF-OST/pytrnsys_gui#63]
Write containment (try... except) around mass flow visualizer for the case that there is an issue with the prt-files (empty or wrong format). At the moment the GUI crashes when such a problem is encountered.

**Comment by martin-neugebauer** [comment]
Having an empty Prt file

![image](https://user-images.githubusercontent.com/67690903/143541367-a6b9bc9a-1d55-4f38-a8d6-2055196b52cc.png)

makes the GUI crash

![image](https://user-images.githubusercontent.com/67690903/143541423-f5f4f483-b7ce-4d92-bd5f-6a45207670c9.png)

**Comment by zuckerruebe** [comment]
Done.
