### ISSUE TITLE
Aborting opening dialogue leads to an open GUI in pytrnsys_gui\trnsysGUI

### ISSUE THREAD

**Issue by martin-neugebauer** [SPF-OST/pytrnsys_gui#66]
When the dialogue to open an existing project is cancelled, the GUI is open in pytrnsys_gui\trnsysGUI with pytrnsys_gui\trnsysGUI\ddck as the ddck-directory. The program should, however, instead return to the dialogue asking whether an existing project should be opened or a new one started.

**Comment by zuckerruebe** [comment]
@martin-neugebauer Could you verify this is fixed, please?

**Comment by martin-neugebauer** [comment]
Verified. :-)

**Comment by zuckerruebe** [comment]
Thanks!
