### ISSUE TITLE
When force-opening same project lots of files get deleted

### ISSUE THREAD

**Issue by zuckerruebe** [SPF-OST/pytrnsys_gui#70]
1. Open `trnsysGUI\examples\TRIHP_dualSource\TRIHP_dualSource.json`.
2. Go to File > Open and open the same file again.
3. Lots of files are deleted:

![image](https://user-images.githubusercontent.com/11159050/119512507-a742e580-bd73-11eb-872c-9f106f9c10eb.png)

**Comment by martin-neugebauer** [comment]
Was this resolved by #73 ?
