### ISSUE TITLE
Enable usage of "delete" key

### ISSUE THREAD

**Issue by martin-neugebauer** [SPF-OST/pytrnsys_gui#86]
Make it possible to delete selected components in the GUI by using the "delete" button on the keyboard

**Comment by simonschlaepfer** [comment]
when deleting a connection with the delete key, sometimes other connections which are not selected are deleted as well

**Comment by martin-neugebauer** [comment]
This behavior is probably related to #181

**Comment by martin-neugebauer** [comment]
closed by #219
