### ISSUE TITLE
Ask whether project should be saved before running TRNSYS

### ISSUE THREAD

**Issue by martin-neugebauer** [SPF-OST/pytrnsys_gui#87]
Ask the user whether they want to save their project before running TRNSYS (mfs or simulation), s. t. no progress is lost if pytrnsys crashes because of TRNSYS problems

(Or even better: Make sure the GUI doesn't crash because of TRNSYS problems)

**Comment by zuckerruebe** [comment]
GUI doesn't crash any more if TRNSYS encounters a problem.
