### ISSUE TITLE
Enable connections between components without them being pipes

### ISSUE THREAD

**Issue by martin-neugebauer** [SPF-OST/pytrnsys_gui#95]
RH pointed out that in TRNSYS studio two components can be connected without the need for a pipe between them. This useful for examples for a valve connected to a radiator, which in reality is done through a short piece of pipe that could be ignored in a simualtion.

**Comment by zuckerruebe** [comment]
What are the disadvantages of just using a short piece of pipe?

**Comment by martin-neugebauer** [comment]
By default we are putting a 2m long pipe with 5 cm diameter between the valve and the radiator, while in reality there is only a very short piece of pipe. So in order to make the simulation realistic, you need to set the pipe to a very short length manually. So in principle we should only set pipes between components if we also care about their physical implications on the simulation.

**Comment by zuckerruebe** [comment]
How about finally tackling being able to set pipe characteristics (length, fluid, ...) from the GUI instead? Would that also help with this issue?

**Comment by martin-neugebauer** [comment]
Yes, that would basically do the same. It's probably still worth to think about enabling a direct connection (i.e. without pipes) between components.

**Comment by zuckerruebe** [comment]
OK...it's just with my current understand this would just add an unneeded extra special case.

**Comment by zuckerruebe** [comment]
> Yes, that would basically do the same. It's probably still worth to think about enabling a direct connection (i.e. without pipes) between components.

Done.

**Comment by zuckerruebe** [comment]
> How about finally tackling being able to set pipe characteristics (length, fluid, ...) from the GUI instead? Would that also help with this issue?

Done.

**Comment by zuckerruebe** [comment]
Double done.
